name: mardegrau
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  carousel_slider: ^3.0.0
  easy_dynamic_theme: ^2.2.0
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  google_sign_in: ^5.0.3
  cloud_firestore: ^2.2.0
  flutter_bloc: ^6.0.5
  equatable: ^1.2.5
  custom_radio_grouped_button: ^1.0.6+1
  gscarousel: ^0.0.1
  line_icons: ^2.0.1
  responsive_table: ^0.1.1+8
  url_launcher:
  provider:
  sliding_up_panel: ^2.0.0+1
  url_strategy: ^0.2.0
  contained_tab_bar_view: ^0.8.0
  timelines: ^0.1.0
#  firebase_storage:
#  image_picker_web:
  firebase:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: Electrolize
      fonts:
        - asset: fonts/Electrolize-Regular.ttf

  assets:
    - assets/images/
